python3: can't open file '/root/vpn_bot_final/main.py': [Errno 2] No such file or directory
python3: can't open file '/root/vpn_bot_final/main.py': [Errno 2] No such file or directory
